#!/usr/bin/env python3
"""Convert published cheats to json/shn/mc4 and update manifests."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TITLES_DIR = ROOT / "titles"
CONVERTER_DIR = ROOT / "ps4_ps5_aio_cheat_converter"
SUPPORTED_FORMATS = ["json", "shn", "mc4"]


def utc_now() -> str:
    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def save_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def load_converter_functions():
    if not CONVERTER_DIR.exists():
        raise SystemExit(f"converter directory not found: {CONVERTER_DIR}")

    sys.path.insert(0, str(CONVERTER_DIR))
    from utilities.json_utilities import shn_to_json_workflow
    from utilities.mc4_utilities import decrypt_mc4_to_shn, encrypt_shn_to_mc4
    from utilities.shn_utilities import json_to_xml_workflow, normalize_xml_entity_idents
    from utilities.catch_exceptions_utilities import escape_ampersand, remove_xml_junk_data

    return {
        "shn_to_json": shn_to_json_workflow,
        "decrypt_mc4": decrypt_mc4_to_shn,
        "encrypt_mc4": encrypt_shn_to_mc4,
        "json_to_shn": json_to_xml_workflow,
        "normalize_shn": normalize_xml_entity_idents,
        "escape_ampersand": escape_ampersand,
        "remove_xml_junk": remove_xml_junk_data,
    }


def read_source_payload(version_dir: Path, manifest: dict, funcs: dict) -> tuple[dict, str]:
    entries = manifest.get("entries", [])
    entry_by_format = {entry.get("format"): entry for entry in entries}

    for fmt in SUPPORTED_FORMATS:
        entry = entry_by_format.get(fmt)
        if not entry:
            continue
        path = version_dir / entry["path"]
        if not path.exists():
            continue

        if fmt == "json":
            json_obj = load_json(path)
            shn_text = funcs["normalize_shn"](funcs["json_to_shn"](json_obj))
            return json_obj, shn_text

        if fmt == "shn":
            raw_text = path.read_text(encoding="utf-8-sig", errors="ignore")
            shn_text = funcs["normalize_shn"](
                funcs["remove_xml_junk"](funcs["escape_ampersand"](raw_text))
            )
            json_obj = funcs["shn_to_json"](shn_text)
            return json_obj, shn_text

        if fmt == "mc4":
            shn_text = funcs["normalize_shn"](funcs["decrypt_mc4"](path.read_bytes()))
            json_obj = funcs["shn_to_json"](shn_text)
            return json_obj, shn_text

    raise ValueError("no readable json/shn/mc4 source entry")


def build_entry(path: Path, fmt: str, cheat_count: int, source_note: str, now: str) -> dict:
    return {
        "format": fmt,
        "path": path.name,
        "size": path.stat().st_size,
        "sha256": sha256_file(path),
        "cheatCount": cheat_count,
        "source": source_note,
        "quality": "imported",
        "updatedAt": now,
        "notes": "Generated by tools/convert_published_cheats.py.",
    }


def convert_manifest(manifest_path: Path, funcs: dict, dry_run: bool) -> dict:
    version_dir = manifest_path.parent
    manifest = load_json(manifest_path)
    title_id = manifest["titleId"]
    version = manifest["version"]
    stem = f"{title_id}_{version}"
    now = utc_now()

    json_obj, shn_text = read_source_payload(version_dir, manifest, funcs)
    json_obj["id"] = title_id
    json_obj["version"] = version
    shn_text = funcs["normalize_shn"](funcs["json_to_shn"](json_obj))
    cheat_count = len(json_obj.get("mods", [])) if isinstance(json_obj.get("mods"), list) else 0
    source_note = manifest.get("notes", "published manifest")

    json_path = version_dir / f"{stem}.json"
    shn_path = version_dir / f"{stem}.shn"
    mc4_path = version_dir / f"{stem}.mc4"

    if not dry_run:
        save_json(json_path, json_obj)
        shn_path.write_text(shn_text, encoding="utf-8")
        mc4_path.write_bytes(funcs["encrypt_mc4"](shn_text))

        entries = [
            build_entry(json_path, "json", cheat_count, source_note, now),
            build_entry(shn_path, "shn", cheat_count, source_note, now),
            build_entry(mc4_path, "mc4", cheat_count, source_note, now),
        ]
        manifest["name"] = json_obj.get("name") or manifest.get("name") or title_id
        manifest["process"] = json_obj.get("process") or manifest.get("process") or "eboot.bin"
        manifest["preferredFormat"] = "json"
        manifest["updatedAt"] = now
        manifest["entries"] = entries
        manifest["notes"] = source_note + " Converted to json/shn/mc4."
        save_json(manifest_path, manifest)

        title_path = version_dir.parent / "title.json"
        title_meta = load_json(title_path)
        if title_meta.get("name") == title_id and json_obj.get("name"):
            title_meta["name"] = json_obj["name"]
            save_json(title_path, title_meta)

    return {
        "manifest": str(manifest_path.relative_to(ROOT)),
        "titleId": title_id,
        "version": version,
        "name": json_obj.get("name", title_id),
        "cheatCount": cheat_count,
        "status": "dry-run" if dry_run else "converted",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--limit", type=int, default=0)
    args = parser.parse_args()

    funcs = load_converter_functions()
    manifests = sorted(TITLES_DIR.glob("*/*/manifest.json"))
    if args.limit:
        manifests = manifests[: args.limit]

    results = []
    failures = []
    for manifest_path in manifests:
        try:
            results.append(convert_manifest(manifest_path, funcs, args.dry_run))
        except Exception as exc:
            failures.append(
                {
                    "manifest": str(manifest_path.relative_to(ROOT)),
                    "error": str(exc),
                }
            )

    print(
        json.dumps(
            {
                "summary": {
                    "converted": len(results) if not args.dry_run else 0,
                    "dryRun": len(results) if args.dry_run else 0,
                    "failed": len(failures),
                },
                "results": results,
                "failures": failures,
            },
            indent=2,
            ensure_ascii=False,
        )
    )
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
